{{- /* chezmoi:modify-template */ -}}
{{- $config := fromToml (default "" .chezmoi.stdin) -}}
{{-
  $config := $config | setValueAtPath "mcp_servers" (
    $config.mcp_servers | default dict | mergeOverwrite .mcpServers
  )
-}}
{{- $config | toToml -}}
