[homebrew.shared]
taps = [
    "oven-sh/bun"
]
brews = [
    "bat",
    "bottom",
    "ccusage",
    "chezmoi",
    "direnv",
    "eza",
    "fd",
    "fzf",
    "gcc",
    "gh",
    "ghq",
    "herdr",
    "jq",
    "lazygit",
    "mise",
    "neovim",
    "ripgrep",
    "rtk",
    "starship",
    "yazi",
    "yq",
    "zoxide",
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    "oven-sh/bun/bun",
]
casks = [
    "codex",
]
mac_casks = [
    "arc",
    "claude",
    "codex-app",
    "codexbar",
    "firefox",
    "font-hackgen-nerd",
    "font-moralerspace",
    "ghostty",
    "karabiner-elements",
    "lm-studio",
    "obsidian",
    "raycast",
    "rectangle",
    "scroll-reverser",
    "visual-studio-code",
    "zed",
    "zen",
]

[homebrew.work]
taps = [
    "datadog-labs/pack",
]
brews = [
    "awscli",
    "azure-cli",
    "colima",
    "crane",
    "docker",
    "docker-buildx",
    "docker-compose",
    "git-secret",
    "gnupg",
    "libomp",
    "datadog-labs/pack/pup",
]
casks = [
    "claude-code@latest",
    "copilot-cli",
    "gcloud-cli",
]
mac_casks = [
    "jetbrains-toolbox",
]

[homebrew.private]
taps = [
    "anomalyco/tap",
]
brews = [
    "anomalyco/tap/opencode",
]
casks = [
]
mac_casks = [
]
