[mcpServers.datadog]
type = "http"
url = "https://mcp.ap1.datadoghq.com/api/unstable/mcp-server/mcp"
headers = {DD_API_KEY = "${DD_API_KEY}", DD_APPLICATION_KEY = "${DD_APPLICATION_KEY}"}

[mcpServers.miro-mcp]
type = "http"
url = "https://mcp.miro.com/"
