[mcp.shared]
[mcp.shared.github]
command = "github-mcp-server-stdio"

[mcp.shared.serena]
command = "serena"
args = ["start-mcp-server", "--project-from-cwd", "--context"]

[mcp.work]

[mcp.private]
[mcp.private.proximo]
command = "uvx"
args = ["proximo-proxmox"]
